name: 'Deploy App'
description: 'Workflow to deploy the App in all environment.'
author: 'TIBCO Software'

  
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev/sit/uat/prod'
#outputs:
#  time:
#   description: 'the greeting time'
         
env:
  WF_ENV: workflow env variable
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: maven build
        run : echo "build completed"
