name: 'Deploy App'
#description: 'Workflow to deploy the App in all environment.'
#author: 'TIBCO Software'
  
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev/sit/uat/prod'
#outputs:
#  time:
#   description: 'the greeting time'
         
env:
  WF_ENV: workflow env variable
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: maven build
        run : |
          echo $OC_SERVER
          echo $SONAR_SERVER
          echo "Build completed"        
        env:
          OC_SERVER: ${{ secrets.OC_SERVER }}
          SONAR_SERVER: ${{ secrets.SONAR_SERVER }}

  code-analysis:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name : Sonar Analysis
        run: echo "Code Analysis completed"

  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: [code-analysis]
    if: ${{ github.event.inputs.environment == 'dev' }}
    steps:
      - name : deploy to dev
        run: |
          echo $OC_PROJECT       
          echo "Deploy to dev completed"
        env:
          OC_PROJECT: ${{ secrets.OC_PROJECT }}

  deploy-sit:
    runs-on: ubuntu-latest
    environment: sit
    needs: [code-analysis]
    if: ${{ github.event.inputs.environment == 'sit' }}
    steps:
      - name : deploy to sit
        run: echo "Deploy to sit completed"
        
  deploy-uat:
    runs-on: ubuntu-latest
    environment: uat
    needs: [code-analysis]
    if: ${{ github.event.inputs.environment == 'uat' }}
    steps:
      - name : deploy to uat
        run: echo "Deploy to uat completed"
        
  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}
    environment: production
    needs: [code-analysis]
    steps:
      - name : deploy to prod
        run: echo "Deploy to prod completed"
      - name : Create release
        run: echo "Deploy to prod completed"